name: CHPL UI Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Run React Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test:react
      env:
        CI: true
    - name: Run Angular Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test
      env:
        CI: true
